name: Widoco

on:
  push:
    branches:
      - '*'
    tags:
      - '*'

jobs:
  widoco:
    runs-on: ubuntu-latest
    steps:
      #
      # Checkout the repo
      #
      - name: Checkout the repo
        uses: actions/checkout@v2

      - name: Widoco
        uses: ./.github/actions/widoco
        with:
          ontologyFile: 'ux-component.ttl'
          ontologyPrefix: 'ekgux'
          ontologyIRI: 'https://ekgf.github.io/o-ux/component#'

      - name: Deploy site
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: html # The folder the action should deploy.
          single-commit: true