name: Widoco

on:
  push:
    branches:
      - '*'
    tags:
      - '*'

jobs:
  widoco:
    runs-on: ubuntu-latest
    steps:
      #
      # Checkout the repo
      #
      - name: Checkout the repo
        uses: actions/checkout@v2

      #
      # Install the right JVM to run Widoco with
      #
      - name: Install the JVM
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '8'

      #
      # Get the version number of the latest widoco jar
      #
      - name: Get widoco version
        id: widocoRelease
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          owner: dgarijo
          repo: WIDOCO
          excludes: prerelease, draft

      #
      # Remove the 'v' from the Widoco release number (to be used to contruct the file name of the jar)
      #
      - name: Strip v from version
        id: widocoRelease2
        run: |
          echo "widoco release: ${{ steps.widocoRelease.outputs.release }}"
          releaseWithVictor="${{ steps.widocoRelease.outputs.release }}"
          releaseWithoutVictor="${releaseWithVictor/v/}"
          echo "::set-output name=release::${releaseWithoutVictor}"

      #
      # Download the latest widoco jar
      #
      - name: Download widoco.jar
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: "dgarijo/WIDOCO"
          version: "tags/${{ steps.widocoRelease.outputs.release }}"
          file: "widoco-${{ steps.widocoRelease2.outputs.release }}-jar-with-dependencies.jar"
          target: "widoco.jar"
          token: ${{ secrets.GITHUB_TOKEN }}

      #
      # Run widoco
      #
      - name: Run Widoco
        run: |
          ls -al
          java \
            -jar widoco.jar \
            -ontFile ux-component.ttl \
            -outFolder ./html \
            -getOntologyMetadata \
            -rewriteAll \
            -ignoreIndividuals \
            -doNotDisplaySerializations \
            -uniteSections
          find docs

      - name: Deploy site
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: html # The folder the action should deploy.
          single-commit: true